### ISSUE TITLE
Plugin requires fixing.

### ISSUE THREAD

**Issue by sunbeam906** [mefistotelis/ida-pro-loadmap#6]
`qstrncpy(g_szIniPath, get_user_idadir(), sizeof(g_szIniPath));`

This piece of code, for me, it returns "C:\\Users\\SunBeam\\AppData\\Roaming\\Hex-Rays\\IDA Pro" (without the ""). As you can see, there's no trailing \\ after Pro. So, naturally, this then happens:

`qstrncat(g_szIniPath, "loadmap.cfg", sizeof(g_szIniPath));`

Which means we get "C:\\Users\\SunBeam\\AppData\\Roaming\\Hex-Rays\\IDA Proloadmap.cfg". Which will never ever be a valid file. So you need a **qstrncat(g_szIniPath, "\\", 1);** right after the first **qstrncpy**.

Because of the above, the plugin always exits; unless fixed as you may have mentioned in another issue I read.

Recommendation:

```
qstrncpy(g_szIniPath, idadir("plugins"), sizeof(g_szIniPath));
qstrncat(g_szIniPath, "\\", sizeof(g_szIniPath));
qstrncat(g_szIniPath, "loadmap.cfg", sizeof(g_szIniPath));
```

This way the 'loadmap.cfg' stays in the plugins directory, where the .dll resides and proper path is computed with trailing slash after first strncpy.

Hope this helps!

**Comment by mefistotelis** [comment]
> Because of the above, the plugin always exits;

It is unlikely that the plugin exists because an unused variable is set incorrectly. But you're right, the path creation is incorrect.

I don't even have a local env to build this.. oh well, will prepare another set of untested changes. Maybe it works.
